# Generated by Django 3.2.7 on 2021-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_cryptor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyGenrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(db_index=True)),
                ('public', models.TextField(db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='path',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='public_key',
            field=models.CharField(default='no key', max_length=4000),
        ),
    ]
