# Generated by Django 3.2.7 on 2021-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_cryptor', '0002_auto_20210930_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
