# Generated by Django 3.2.7 on 2021-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_cryptor', '0003_alter_imagefile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
