# Generated by Django 3.2.7 on 2021-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_cryptor', '0004_alter_imagefile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keygenrator',
            name='private_key',
            field=models.FileField(db_index=True, upload_to='keys'),
        ),
        migrations.AlterField(
            model_name='keygenrator',
            name='public',
            field=models.FileField(db_index=True, upload_to='key'),
        ),
    ]
