# Generated by Django 3.1.5 on 2021-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_cryptor', '0005_auto_20210930_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='public_key',
            field=models.FileField(upload_to='public_keys'),
        ),
        migrations.AlterField(
            model_name='keygenrator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
