# Generated by Django 3.1.5 on 2021-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_cryptor', '0006_auto_20211013_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.FileField(upload_to='private_keys')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
